version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: sheeps_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sheeps
    ports:
      - "5432:5432"
    volumes:
      - sheeps_data:/var/lib/postgresql/data

volumes:
  sheeps_data:
